name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      publish_release: true
      release_tag: rolling
      release_name: Latest
